Repository jquery/jquery, pull requests merged in 2018-07, with the labels that each got.

#4122 Tests: Add support test results for Firefox 61+
  test/unit/support.js
Labels: Needs review, Tests

#4125 Manipulation: Properly detect HTML elements with single-character names
  src/core/var/rsingleTag.js
  src/manipulation/var/rtagName.js
  test/unit/manipulation.js
Labels: Manipulation

#4140 Tests: Skip module tests in Edge
  test/unit/manipulation.js
Labels: Tests
