Repository jquery/jquery, pull requests merged in 2020-04, with the labels that each got.

#4656 Event: Use only one focusin/out handler per matching window & document
  src/event/focusin.js
  test/unit/event.js
Labels: Bug, Event

#4650 Ajax: Overwrite s.contentType with content-type header value, if any
  src/ajax.js
  test/unit/ajax.js
Labels: Ajax

#4673 Docs: Use https for hyperlinks in README
  build/fixtures/README.md
Labels: Docs

#4666 Data: Make the data object a regular object again
  src/data/Data.js
  test/unit/data.js
Labels: 3.x-only, Data, Discuss in Meeting, Needs review

#4520 Build: Enable reportUnusedDisableDirectives in ESLint
  .eslintrc-browser.json
  .eslintrc-node.json
Labels: Build

#4678 Build: Test on Node.js 14, stop testing on Node.js 8 & 13
  .travis.yml
Labels: Build

#4684 Docs: Update the link to the jsdom repository
  build/fixtures/README.md
Labels: Docs

#4687 Tests: Fix flakiness in the "jQuery.ajax() - JSONP - Same Domain" test
  test/middleware-mockserver.js
Labels: Tests

#4676 Build: Move ESLint max-len disable-directive to dist/.eslintrc.json
  dist/.eslintrc.json
  src/core.js
Labels: Build

#4657 Tests: Use only one focusin/out handler per matching window & document
  test/unit/event.js
Labels: Tests

#4649 Build: Reduce the slim build header comment & jQuery.fn.jquery
  build/tasks/build.js
Labels: Build

#4685 Tests: Add tests for recently fixed manipulation XSS issues
  test/unit/manipulation.js
Labels: Needs review, Tests

#4686 Docs: Fix typos
  build/fixtures/README.md
  test/unit/manipulation.js
Labels: Docs

#4694 Tests: Workaround failures in recent XSS tests in iOS 8 - 12
  test/unit/manipulation.js
Labels: Tests
