Repository jquery/jquery, pull requests merged in 2020-07, with the labels that each got.

#4732 Build: Update dependencies
  package.json
Labels: Build, Needs review

#4737 Build: Fix commitplease husky config
  package.json
Labels: Build

#4753 Revert "Offset: Send px-ed strings to .css()"
  src/offset.js
Labels: Needs review, Offset

#4752 Build: Use the US spelling of "favor"
  test/index.html
  test/karma.context.html
  test/karma.debug.html
Labels: Build, Needs review

#4754 Ajax: Drop the json to jsonp auto-promotion logic
  src/ajax/jsonp.js
  test/data/mock.php
  test/middleware-mockserver.js
  test/unit/ajax.js
Labels: Ajax, Behavior Change

#4757 Core: Bring back QtWebKit support for jQuery 3.x
  src/var/isFunction.js
Labels: Core
