Repository jquery/jquery, pull requests merged in 2021-11, with the labels that each got.

#4949 Attributes: Don't stringify attributes in the setter
  src/attributes/attr.js
  test/data/mock.php
  test/data/trusted-types-attributes.html
  test/data/trusted-types-attributes.js
  test/middleware-mockserver.js
  test/unit/attributes.js
Labels: Attributes

#4966 Tests: Disable CSS Custom Properties tests in old Safari/iOS
  test/unit/css.js
Labels: Tests

#4972 Docs: Update the URL to the latest jQuery build in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Docs

#4800 Build: Migrate CI to GitHub Actions
  .github/workflows/node.js.yml
  Gruntfile.js
Labels: Build
