Repository jquery/jquery, pull requests merged in 2022-06, with the labels that each got.

#5057 Build: Add dependabot.yml config (GitHub Actions)
  .github/dependabot.yml
Labels: Needs review, Build

#5067 Build: Update GitHub Actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
Labels: Build, dependencies

#5046 Tests: Exclude tests based on compilation flags, not API presence
  build/tasks/build.js
  build/tasks/lib/slim-build-flags.js
  test/.eslintrc.json
  test/data/testinit-jsdom.js
  test/data/testinit.js
  test/unit/ajax.js
  test/unit/animation.js
  test/unit/attributes.js
  test/unit/basic.js
  test/unit/callbacks.js
  test/unit/core.js
  test/unit/css.js
  test/unit/deferred.js
  test/unit/deprecated.js
  test/unit/dimensions.js
  test/unit/effects.js
  test/unit/manipulation.js
  test/unit/offset.js
  test/unit/queue.js
  test/unit/ready.js
  test/unit/serialize.js
  test/unit/support.js
  test/unit/tween.js
  test/unit/wrap.js
Labels: Tests
