Repository jquery/jquery, pull requests merged in 2022-07, with the labels that each got.

#5071 Tests: Exclude tests based on compilation flags, not API presence (3.x version)
  build/tasks/build.js
  build/tasks/lib/slim-build-flags.js
  test/.eslintrc.json
  test/data/testinit-jsdom.js
  test/data/testinit.js
  test/unit/ajax.js
  test/unit/animation.js
  test/unit/attributes.js
  test/unit/basic.js
  test/unit/callbacks.js
  test/unit/core.js
  test/unit/css.js
  test/unit/deferred.js
  test/unit/deprecated.js
  test/unit/dimensions.js
  test/unit/effects.js
  test/unit/manipulation.js
  test/unit/offset.js
  test/unit/queue.js
  test/unit/ready.js
  test/unit/serialize.js
  test/unit/support.js
  test/unit/tween.js
  test/unit/wrap.js
Labels: Tests

#5037 Docs: Update webpack website in README
  build/fixtures/README.md
Labels: Docs

#5036 chore: remove git.io
  .github/workflows/codeql-analysis.yml
Labels: Build
