Repository jquery/jquery, pull requests merged in 2022-01, with the labels that each got.

#4993 Docs: Replace `#NUMBER` Trac issue references with `trac-NUMBER`
  README.md
  src/ajax.js
  src/ajax/xhr.js
  src/attributes/prop.js
  src/attributes/val.js
  src/core/init.js
  src/core/ready-no-deferred.js
  src/core/ready.js
  src/css.js
  src/css/cssCamelCase.js
  src/data.js
  src/data/Data.js
  src/event.js
  src/event/trigger.js
  src/exports/global.js
  src/manipulation.js
  src/manipulation/_evalUrl.js
  src/manipulation/buildFragment.js
  src/manipulation/getAll.js
  src/selector.js
  src/wrapper.js
  test/data/ajax/onunload.html
  test/data/core/aliased.html
  test/data/core/onready.html
  test/data/data/dataAttrs.html
  test/data/event/focusElem.html
  test/data/event/focusinCrossFrame.html
  test/data/event/promiseReady.html
  test/data/event/syncReady.html
  test/data/readywait.html
  test/data/testsuite.css
  test/networkerror.html
  test/unit/ajax.js
  test/unit/attributes.js
  test/unit/callbacks.js
  test/unit/core.js
  test/unit/css.js
  test/unit/data.js
  test/unit/deprecated.js
  test/unit/dimensions.js
  test/unit/effects.js
  test/unit/event.js
  test/unit/manipulation.js
  test/unit/offset.js
  test/unit/queue.js
  test/unit/selector.js
  test/unit/serialize.js
  test/unit/support.js
  test/unit/traversing.js
  test/unit/wrap.js
Labels: Docs

#4992 Build: Separate the install step from running tests in GitHub Actions
  .github/workflows/node.js.yml
Labels: Build

#4991 Docs: Remove links to Web Archive from source
  src/attributes/prop.js
  src/queue/delay.js
Labels: Docs

#4999 Docs: remove expired links from old jquery source
  test/data/jquery-1.9.1.js
Labels: Docs

#4994 Docs: Replace `#NUMBER` Trac issue references with `trac-NUMBER`
  README.md
  src/ajax.js
  src/ajax/xhr.js
  src/attributes/prop.js
  src/attributes/val.js
  src/core/camelCase.js
  src/core/init.js
  src/core/ready-no-deferred.js
  src/core/ready.js
  src/css.js
  src/css/curCSS.js
  src/css/support.js
  src/css/var/getStyles.js
  src/data.js
  src/data/Data.js
  src/effects.js
  src/event.js
  src/event/trigger.js
  src/exports/global.js
  src/manipulation.js
  src/manipulation/_evalUrl.js
  src/manipulation/buildFragment.js
  src/manipulation/getAll.js
  src/manipulation/support.js
  src/manipulation/wrapMap.js
  src/selector-native.js
  src/wrapper.js
  test/data/ajax/onunload.html
  test/data/core/aliased.html
  test/data/core/onready.html
  test/data/data/dataAttrs.html
  test/data/event/focusElem.html
  test/data/event/focusinCrossFrame.html
  test/data/event/promiseReady.html
  test/data/event/syncReady.html
  test/data/readywait.html
  test/data/testsuite.css
  test/networkerror.html
  test/unit/ajax.js
  test/unit/attributes.js
  test/unit/callbacks.js
  test/unit/core.js
  test/unit/css.js
  test/unit/data.js
  test/unit/deprecated.js
  test/unit/dimensions.js
  test/unit/effects.js
  test/unit/event.js
  test/unit/manipulation.js
  test/unit/offset.js
  test/unit/queue.js
  test/unit/selector.js
  test/unit/serialize.js
  test/unit/support.js
  test/unit/traversing.js
  test/unit/wrap.js
Labels: Needs review, Docs

#4995 Docs: Fix incorrect `trac-NUMBER` references
  test/unit/ajax.js
  test/unit/core.js
  test/unit/css.js
  test/unit/data.js
  test/unit/effects.js
  test/unit/manipulation.js
  test/unit/selector.js
Labels: Docs

#4986 Core: Don't rely on splice being present on input
  src/selector/uniqueSort.js
  src/var/splice.js
  test/unit/selector.js
Labels: Core, Discuss in Meeting

#5003 CSS: Skip falsy values in `addClass( array )`, compress code
  src/attributes/classes.js
  test/unit/attributes.js
Labels: CSS
