Repository jquery/jquery, pull requests merged in 2024-05, with the labels that each got.

#5466 Event: Increase robustness of an inner native event in leverageNative
  src/event.js
  test/unit/event.js
Labels: Event

#5492 Tests: revert concurrency group change
  .github/workflows/browserstack.yml
Labels: Tests

#5493 Tests: revert concurrency group change
  .github/workflows/browserstack.yml
Labels: Tests

#5497 Tests: Make `:has` selector tests not vulnerable to unrelated failures
  test/unit/selector.js
Labels: Needs review, Tests

#5498 Tests: Align `:has` selector tests with `3.x-stable`
  test/unit/selector.js
Labels: Needs review, Tests
