Repository jquery/jquery, pull requests merged in 2024-04, with the labels that each got.

#5460 Tests: share queue/browser handling for all worker types
  test/runner/browsers.js
  test/runner/browserstack/browsers.js
  test/runner/command.js
  test/runner/flags/browsers.js
  test/runner/flags/modules.js
  test/runner/jsdom.js
  test/runner/jsdom/createWindow.js
  test/runner/queue.js
  test/runner/reporter.js
  test/runner/run.js
  test/runner/selenium/createDriver.js
  test/runner/selenium/queue.js
  test/runner/selenium/runSelenium.js
Labels: Tests

#5465 Tests: share queue/browser handling for all worker types
  test/runner/browsers.js
  test/runner/browserstack/browsers.js
  test/runner/command.js
  test/runner/flags/browsers.js
  test/runner/flags/modules.js
  test/runner/jsdom.js
  test/runner/jsdom/createWindow.js
  test/runner/queue.js
  test/runner/reporter.js
  test/runner/run.js
  test/runner/selenium/createDriver.js
  test/runner/selenium/queue.js
  test/runner/selenium/runSelenium.js
Labels: Tests

#4861 Offset: Increase search depth when finding the 'real' offset parent
  src/offset.js
  test/unit/offset.js
Labels: Needs review, Offset, Discuss in Meeting

#5479 Docs: Update remaining HTTP URLs to HTTPS
  README.md
  build/fixtures/README.md
Labels: Needs review, Docs

#5481 Tests: include github ref in concurrency group
  .github/workflows/browserstack.yml
Labels: Tests

#5482 Tests: include github ref in concurrency group
  .github/workflows/browserstack.yml
Labels: Tests
