Repository jquery/jquery, pull requests merged in 2024-10, with the labels that each got.

#5563 Build: Enforce ECMAScript 5 in tests via ESLint
  eslint.config.js
Labels: Build

#5565 Docs: add version support section to README
  README.md
Labels: Docs

#5564 Docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Docs

#5567 Docs: Align CONTRIBUTING.md with `3.x-stable`
  CONTRIBUTING.md
Labels: Needs review, Build
