Repository jquery/jquery, pull requests merged in 2024-09, with the labels that each got.

#5547 Tests: Run tests on both real Firefox ESRs
  .github/workflows/browserstack.yml
  .github/workflows/node.js.yml
Labels: Needs review

#5548 Tests: Run tests on both real Firefox ESRs
  .github/workflows/node.js.yml
Labels: Tests

#5540 Tests: Run tests in Edge in IE mode in GitHub Actions
  .github/workflows/node.js.yml
  package.json
  test/runner/selenium/createDriver.js
Labels: Build

#5523 Manipulation: Make jQuery.cleanData not skip elements during cleanup
  src/manipulation/getAll.js
  test/unit/manipulation.js
Labels: Manipulation

#5559 Tests: Switch to an updated fork of promises-aplus-tests
  package-lock.json
  package.json
Labels: Tests
