Repository jquery/jquery, pull requests merged in 2024-06, with the labels that each got.

#5495 CSS:Tests: Fix tests & support tests under CSS Zoom
  src/css/support.js
  test/data/support/zoom.html
  test/unit/css.js
  test/unit/support.js
Labels: CSS, Needs review, Tests

#5503 Build: Group dependabot PRs updating GitHub Actions
  .github/dependabot.yml
Labels: Build

#5501 Build: improve specificity of eslint config; add ecma versions
  eslint.config.js
  test/bundler_smoke_tests/run-jsdom-tests.js
  test/data/csp-nonce-external.js
  test/data/csp-nonce-globaleval.js
  test/data/csp-nonce.js
  test/jquery.js
  test/unit/attributes.js
  test/unit/css.js
  test/unit/data.js
  test/unit/deferred.js
  test/unit/effects.js
  test/unit/event.js
  test/unit/manipulation.js
  test/unit/offset.js
  test/unit/traversing.js
Labels: Build

#5506 Tests: fix supportsScroll feature test in offset
  test/unit/offset.js
Labels: Blocker, Tests

#5507 Tests: remove unnecessary scroll feature test
  test/unit/offset.js
Labels: Blocker, Tests

#5508 Build: upgrade dependencies, including eslint 9.4.0 and uglify 3.7.7
  .gitignore
  build/tasks/build.js
  build/tasks/compare_size.mjs
  build/tasks/promises_aplus_tests.js
  eslint.config.js
  package-lock.json
  package.json
  src/ajax.js
  src/ajax/xhr.js
  src/attributes/prop.js
  src/core/parseXML.js
  src/data.js
  src/manipulation.js
  src/selector.js
  test/unit/ajax.js
  test/unit/attributes.js
  test/unit/css.js
  test/unit/deprecated.js
  test/unit/event.js
  test/unit/manipulation.js
Labels: Build

#5509 Build: upgrade dependencies; fix bundler tests on windows
  build/tasks/promises_aplus_tests.js
  eslint.config.js
  package-lock.json
  package.json
  test/bundler_smoke_tests/lib/run-webpack.js
Labels: Build
