Repository jquery/jquery, pull requests merged in 2024-03, with the labels that each got.

#5427 Migrate testing infrastructure on 3.x-stable
  .github/workflows/browserstack-dispatch.yml
  .github/workflows/browserstack.yml
  .github/workflows/node.js.yml
  .gitignore
  CONTRIBUTING.md
  Gruntfile.js
  build/grunt-tasks/testswarm.js
  build/tasks/lib/verifyNodeVersion.js
  eslint.config.js
  package-lock.json
  package.json
  test/data/core/dynamic_ready.html
  test/data/jquery-1.9.1.js
  test/data/jquery-3.7.1.js
  test/data/testinit-jsdom.js
  test/data/testinit.js
  test/index.html
  test/jquery.js
  test/karma.context.html
  test/karma.debug.html
  test/middleware-mockserver.js
  test/runner/browsers.js
  test/runner/browserstack/api.js
  test/runner/browserstack/browsers.js
  test/runner/browserstack/buildBrowserFromString.js
  test/runner/browserstack/createAuthHeader.js
  test/runner/browserstack/local.js
  test/runner/browserstack/queue.js
  test/runner/command.js
  test/runner/createTestServer.js
  test/runner/jsdom.js
  test/runner/lib/buildTestUrl.js
  test/runner/lib/generateHash.js
  test/runner/lib/getBrowserString.js
  test/runner/lib/prettyMs.js
  test/runner/listeners.js
  test/runner/modules.js
  test/runner/package.json
  test/runner/reporter.js
  test/runner/run.js
  test/runner/selenium/createDriver.js
  test/runner/selenium/queue.js
  test/runner/selenium/runSelenium.js
  test/runner/server.js
  test/server.js
  test/unit/ajax.js
  test/unit/animation.js
  test/unit/core.js
  test/unit/effects.js
  test/unit/event.js
  test/unit/selector.js
  test/unit/support.js
  test/unit/tween.js
Labels: Tests

#5428 Tests: reuse browser workers in BrowserStack tests
  .github/workflows/browserstack.yml
  eslint.config.js
  package.json
  test/data/testinit.js
  test/index.html
  test/runner/browserstack/api.js
  test/runner/browserstack/browsers.js
  test/runner/browserstack/buildBrowserFromString.js
  test/runner/browserstack/queue.js
  test/runner/browserstack/workers.js
  test/runner/command.js
  test/runner/createTestServer.js
  test/runner/jsdom.js
  test/runner/listeners.js
  test/runner/run.js
  test/runner/selenium/createDriver.js
  test/runner/selenium/queue.js
  test/runner/selenium/runSelenium.js
Labels: Needs review, Tests

#5435 Build: add GitHub Actions workflow to update Filestash
  .github/workflows/filestash.yml
Labels: Build

#5439 Tests: add --hard-retries option to test runner
  .github/workflows/browserstack.yml
  test/runner/browserstack/browsers.js
  test/runner/browserstack/queue.js
  test/runner/command.js
  test/runner/createTestServer.js
  test/runner/run.js
Labels: Tests

#5429 Core: Fix the exports setup to make bundlers work with ESM & CommonJS
  .gitignore
  build/fixtures/README.md
  build/release/dist.js
  build/tasks/node_smoke_tests.js
  dist-module/jquery.node-module-wrapper.js
  dist-module/jquery.node-module-wrapper.slim.js
  dist/jquery.bundler-require-wrapper.js
  dist/jquery.bundler-require-wrapper.slim.js
  eslint.config.js
  package-lock.json
  package.json
  test/bundler_smoke_tests/lib/run-rollup.js
  test/bundler_smoke_tests/lib/run-webpack.js
  test/bundler_smoke_tests/lib/utils.js
  test/bundler_smoke_tests/rollup-commonjs.config.js
  test/bundler_smoke_tests/rollup-pure-esm.config.js
  test/bundler_smoke_tests/run-jsdom-tests.js
  test/bundler_smoke_tests/src-esm-commonjs/jquery-require.cjs
  test/bundler_smoke_tests/src-esm-commonjs/main.js
  test/bundler_smoke_tests/src-pure-esm/main.js
  test/bundler_smoke_tests/test.html
  test/bundler_smoke_tests/webpack.config.cjs
  test/node_smoke_tests/commonjs/factory/document_missing.cjs
  test/node_smoke_tests/commonjs/lib/ensure_global_not_created.cjs
  test/node_smoke_tests/commonjs/lib/ensure_iterability_es6.cjs
  test/node_smoke_tests/commonjs/lib/ensure_jquery.cjs
  test/node_smoke_tests/dual/factory/import-and-require-factory.js
  test/node_smoke_tests/dual/lib/jquery-require-factory.cjs
  test/node_smoke_tests/dual/lib/jquery-require.cjs
  test/node_smoke_tests/dual/regular/import-and-require.js
  test/node_smoke_tests/module/factory/document_missing.js
  test/node_smoke_tests/module/lib/ensure_global_not_created.js
  test/node_smoke_tests/module/lib/ensure_iterability_es6.js
  test/node_smoke_tests/module/lib/ensure_jquery.js
  test/node_smoke_tests/module/regular/window_present_originally.js
Labels: Core

#5443 Tests: add actual and expected messages to test reporter
  test/runner/reporter.js
Labels: Tests

#5444 Tests: add actual and expected messages to test reporter
  test/runner/reporter.js
Labels: Tests

#5445 Tests: add diffing to test reporter
  package-lock.json
  package.json
  test/runner/reporter.js
Labels: Tests

#5446 Tests: add diffing to test reporter
  package-lock.json
  package.json
  test/runner/reporter.js
Labels: Tests

#5448 Tests: show any and all actual/expected values
  test/runner/reporter.js
Labels: Tests

#5449 Tests: show any and all actual/expected values
  test/runner/reporter.js
Labels: Tests

#5452 Attributes: Make `.attr( name, false )` remove for all non-ARIA attrs
  src/attributes/attr.js
  test/unit/attributes.js
  test/unit/selector.js
Labels: Behavior Change, Attributes

#5454 Tests: improve diffing for values of different types
  test/runner/listeners.js
  test/runner/reporter.js
Labels: Tests

#5455 Tests: improve diffing for values of different types
  test/runner/listeners.js
  test/runner/reporter.js
Labels: Tests
